import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect, useState } from 'react'

const link = ' https://pokeapi.co/api/v2/pokemon/'

// export async function getServerSideProps() {
//   const res = await fetch(link)
//   const data = await res.json()
//   const { results = [] } = await data;

//   const pokemon = await Promise.all(results.map(async result => {
//     const { url } = result
//     const pokeRes = await fetch(url)
//     return await pokeRes.json()
//   }))
//   return {
//     props: {
//       data,
//       pokemon
//     }
//   }
// }
// const arr=[]

// export default function Home({ data, pokemon }) {

//   const [allPokemon,setAllPokemon]=useState([])
//   const [loadMore,setLoadMore]=useState(link)

//   const getAllPokemon = async () =>{
//     const res = await fetch(loadMore)
//     const data = await res.json()
//     const { results = [] } = await data;
//     setLoadMore(data.next)
  
//     const pokemon = await Promise.all(results.map(async result => {
//       const { name } = result

//       const pokeRes = await fetch(`${link}${name}`)
//       setAllPokemon( currentList => [...currentList, pokeRes])
//       arr.push(pokeRes)
//       return await pokeRes.json()
//     }))
//     // setAllPokemon(cuurentList=>{return [...cuurentList, pokemon]})
//     console.log(arr);
//     console.log(pokemon);
// console.log(allPokemon);
//   }

//   useEffect(() => {

    
// getAllPokemon()

//   },[])

//   console.log(data);
//   console.log(pokemon);
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"></link>
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//          Pikachu

//         </h1>

//         <p className={styles.description}>
// Pokemon World

//         </p>
//         {/* <form className='search' onSubmit={handleOnSubmitSearch}>
//           <input value={value} onChange={(e)=>changeValue(e.target.value)} type="search" name='query' />
//           <button>Search</button>
//         </form> */}


//         <div className={styles.grid}>
//           {allPokemon.map(result => {
//             const { id, name,  } = result
//             // const image = result.sprites.other.dream_world.front_default


//             return (
//               <li key={id} className={styles.card}>
//   <Link href="/charcter/[id]" as={`/charcter/${id}`}>
//                 <a >
//                   {/* <img src={image} alt={name} /> */}
//                   <h2>{name} </h2>

//                 </a>
//                 </Link>
//               </li>
//             )
//           })}



//         </div>
//         <button onClick={getAllPokemon}>Load more</button>
//       </main>


//     </div>
//   )
// }
const App = () => {

  const[allPokemons, setAllPokemons] = useState([])
  const [loadMore, setLoadMore] = useState('https://pokeapi.co/api/v2/pokemon?limit=20')

 const getAllPokemons = async () => {
   const res = await fetch(loadMore)
   const data = await res.json()

   setLoadMore(data.next)

   function createPokemonObject(results)  {
     results.forEach( async pokemon => {
       const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${pokemon.name}`)
       const data =  await res.json()
       setAllPokemons( currentList => [...currentList, data])
       await allPokemons.sort((a, b) => a.id - b.id)
     })
   }
   createPokemonObject(data.results)
   console.log(allPokemons);
 }

useEffect(() => {
 getAllPokemons()
}, [])

 return (
   <div className="app-contaner">
     <h1>Pokemon Evolution</h1>
     <div className="pokemon-container">
       <div className="all-container">
         
           <div className={styles.grid} >
                 {allPokemons.map(result => {
                       const { id, name,  } = result
                       const image = result.sprites.other.dream_world.front_default
           
           
                       return (
                         <li key={id} className={styles.card}>
             <Link href="/charter/[id]" as={`/charter/${id}`}>
                           <a >
                             <img src={image} alt={name} />
                             <h2>{name} </h2>
           
                           </a>
                           </Link>
                         </li>
                       )
                     })}
           
           
           
                   </div>
                   
         
       </div>
         <button  onClick={() => getAllPokemons()}>Load more</button>
     </div>
   </div>
 );
}

export default App;