import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const defaultEndpoint = 'https://rickandmortyapi.com/api/character'
export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint)
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}

export default function Home({ data }) {
  console.log(data);
  const [value,changeValue]= useState('')
  const { info, results: defaultresults = [] } = data
  const [results, updateResults] = useState(defaultresults)
  const [page, updatePage] = useState({
    ...info,
    current: defaultEndpoint
  })
  const { current } = page
  console.log(value);

  function handleOnSubmitSearch(e) {
    e.preventDefault();
  
    // const { currentTarget = {} } = e;
    // const fields = Array.from(currentTarget?.elements);
    // const fieldQuery = fields.find(field => field.name === 'query');
  
    // const value = fieldQuery.value || '';
    const endpoint = `https://rickandmortyapi.com/api/character/?name=${value}`;
  
    updatePage({
      current: endpoint
    });
  }
  

  useEffect(() => {
    if (current === defaultEndpoint) return;

    async function request() {
      const res = await fetch(current)
      const nextData = await res.json();

      updatePage({
        current,
        ...nextData.info
      });

      if (!nextData.info?.prev) {
        updateResults(nextData.results);
        return;
      }

      updateResults(prev => {
        return [
          ...prev,
          ...nextData.results
        ]
      });
    }

    request();
  }, [current]);
  // console.log(results);
  function handleLoadMOre() {
    updatePage(prev => {
      console.log(page);
      return {
        ...prev,
        current: page?.next
      }
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>        Wubba Lubba dub dub?
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Wubba Lubba dub dub?

        </h1>

        <p className={styles.description}>
          Rick and morty wiki

        </p>
        <form className='search' onSubmit={handleOnSubmitSearch}>
          <input value={value} onChange={(e)=>changeValue(e.target.value)} type="search" name='query' />
          <button>Search</button>
        </form>


        <div className={styles.grid}>
          {results.map(result => {
            const { id, name, image } = result


            return (
              <li key={id} className={styles.card}>
  <Link href="/charcter/[id]" as={`/charcter/${id}`}>
                <a >
                  <img src={image} alt={name} />
                  <h2>{name} </h2>

                </a>
                </Link>
              </li>
            )
          })}



        </div>
        <button onClick={handleLoadMOre}>Load more</button>
      </main>


    </div>
  )
}
